# Generated by Django 2.1 on 2018-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('someAttr1', models.CharField(max_length=30)),
                ('someAttr2', models.CharField(max_length=30)),
                ('someAttr3', models.CharField(max_length=30)),
                ('someAttr4', models.CharField(max_length=30)),
                ('someAttr5', models.CharField(max_length=30)),
                ('someAttr6', models.CharField(max_length=30)),
                ('someAttr7', models.CharField(max_length=30)),
                ('someAttr8', models.CharField(max_length=30)),
                ('someAttr9', models.CharField(max_length=30)),
                ('someAttr10', models.CharField(max_length=30)),
                ('someAttr11', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('pnumber', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
