# Generated by Django 2.1 on 2018-09-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatable',
            old_name='someAttr1',
            new_name='avg_speed',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='someAttr10',
            new_name='download',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='someAttr11',
            new_name='download_speed',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='someAttr2',
            new_name='last_tested',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='someAttr3',
            new_name='ping_RTT',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='someAttr4',
            new_name='server',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='someAttr5',
            new_name='upload_speed',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='someAttr6',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='someAttr7',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='someAttr8',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='someAttr9',
        ),
    ]
