# Generated by Django 2.1 on 2018-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180914_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=30)),
                ('last_tested', models.CharField(max_length=30)),
                ('avg_speed', models.CharField(max_length=30)),
                ('ping_RTT', models.CharField(max_length=30)),
                ('upload_speed', models.CharField(max_length=30)),
                ('download_speed', models.CharField(max_length=30)),
                ('download', models.CharField(max_length=30)),
            ],
        ),
    ]
